name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with build arguments
        run: docker build --build-arg BUILD_PORT=${{ vars.PORT_DOCKER }} -t nextjsapp:test .

      - name: Run Jest tests inside the container
        id: test
        run: |
          set -e  # Stop on failure
          docker run --rm nextjsapp:test npx jest

      - name: Tag the image
        if: success()
        run: docker tag nextjsapp:test ${{ vars.DOCKER_USERNAME }}/nextjsapp:${{ github.sha }}

      - name: Push to Docker Hub
        if: success()
        run: docker push ${{ vars.DOCKER_USERNAME }}/nextjsapp:${{ github.sha }}

      - name: Run Docker Container
        run: docker run -d -p ${{ vars.PORT_DOCKER }}:3000 --name dockertest nextjsapp:${{ github.sha }}
